---
- hosts:
    - leafs
    - spines
  become: yes
  become_user: cumulus
  tasks:
    - name: fetch ports.conf
      fetch: dest=backup/{{ansible_hostname}}/ports.conf src=/etc/cumulus/ports.conf flat=yes

    - name: fetch interfaces
      fetch: dest=backup/{{ansible_hostname}}/interfaces src=/etc/network/interfaces flat=yes

    - name: copy frr daemons file
      fetch: dest=backup/{{ansible_hostname}}/frr/daemons src=/etc/frr/daemons flat=yes

    - name: copy frr.conf
      fetch: dest=backup/{{ansible_hostname}}/frr/frr.conf src=/etc/frr/frr.conf flat=yes
