---
- hosts:
    - leafs
    - spines
  become: 'yes'
  become_method: sudo
  remote_user: cumulus
  become_user: cumulus
  vars:
    ansible_become_pass: 'CumulusLinux!'
  tasks:
    - name: copy ports.conf
      copy: src=backup/{{ansible_hostname}}/ports.conf dest=/etc/cumulus/ports.conf

    - name: copy interfaces
      copy: src=backup/{{ansible_hostname}}/interfaces dest=/etc/network/interfaces

    - name: copy frr daemons file
      copy: src=backup/{{ansible_hostname}}/frr/daemons dest=/etc/frr/daemons

    - name: copy frr.conf
      copy: src=backup/{{ansible_hostname}}/frr/frr.conf dest=/etc/frr/frr.conf

    #- name: reload switchd
    #  service: name=switchd state=restarted

    #- name: reload networking
    #  command: ifreload -a

#    - name: reload frr
#      service:
#        name: 'frr'
#        enabled: yes
#        state: restarted
