---

- hosts:
    - leafs
    - spines
  become_user: cumulus
  become: yes
  become_method: sudo

  handlers:
    - name: reload networking
      command: "{{item}}"
      with_items:
        - ifreload -a
        - sleep 10

    - name: restart frr
      service: name=frr state=restarted

  roles:
    - interfaces
    - routing
