---

- hosts:
    - leafs
    - spines
  become_user: root
  become: yes
  become_method: sudo

  handlers:
    - name: reload networking
      command: "{{item}}"
      with_items:
        - ifreload -a
        - sleep 10

  roles:
    - interfaces
