---
- name: ensure FRR is running
  service: name=frr enabled=yes state=started

- name: write the FRR daemons settings
  template: src=templates/daemons.j2 dest=/etc/frr/daemons
  notify:
    - restart frr

- name: write the FRR config file
  template: src=templates/frr.j2 dest=/etc/frr/frr.conf
  notify:
    - restart frr
